In [1]:
from scipy.stats import ks_2samp

In [2]:
import numpy as np

In [7]:
arr1 = np.arange(10)
arr2 = np.arange(10,20)

In [8]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
res = ks_2samp(arr1,arr2)

In [12]:
res.pvalue

1.0825088224469026e-05

In [13]:
round(res.pvalue)

0

In [15]:
arr3 = np.arange(10)
arr4 = np.arange(10)

In [16]:
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
res2 = ks_2samp(arr3,arr4)

In [20]:
res2.pvalue

1.0

In [21]:
round(res2.pvalue)

1

In [24]:
 ## null: two dataset are from the same distribution

 ## alternate : the two dataset are not from the the same distribution

 ## if p >== 0.05 :
 ## we have sufficient proof that the null hypothesis is True

 ## else:
 ##   we dont have sufficient proof that null hypothesis is True

In [27]:
res=ks_2samp(arr3,arr4)
round(res.pvalue,2)

1.0